version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - education-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - education-network

networks:
  education-network:
    driver: bridge
