version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/education-platform
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - education-network

  mongodb:
    image: mongo:6.0
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=education-platform
    volumes:
      - mongodb_data:/data/db
    networks:
      - education-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - education-network

volumes:
  mongodb_data:

networks:
  education-network:
    driver: bridge
