export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY';
export const EMAIL_SERVICE_TOKEN = 'EMAIL_SERVICE';
export const COURSE_REPOSITORY_TOKEN = 'COURSE_REPOSITORY';
export const SESSION_REPOSITORY_TOKEN = 'SESSION_REPOSITORY';
